variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  VERSIONING_DISABLE: "false"
  VERSIONING_GIT_TAG: $CI_COMMIT_TAG
  VERSIONING_GIT_BRANCH: $CI_COMMIT_BRANCH

default:
  cache:
    paths:
      - .m2/repository/
  tags:
    - qlf-ci.inria.fr

stages:
  - build
  - quality

build:
  image: maven:3.6.3-adoptopenjdk-11
  stage: build
  script:
    - mvn -B -s .mvn/settings-ci.xml verify
  artifacts:
    paths:
      - target/
    reports:
      junit:
        - target/*-reports/TEST-*.xml

quality:
  image: maven:3.6.3-adoptopenjdk-11
  stage: quality
  needs:
    - build
  variables:
    GIT_DEPTH: 0  # Tells git to fetch all the branches of the project, required by the analysis task
  script:
    - mvn -B spotless:check jacoco:report
    - mvn -B -Dformats=HTML,JUNIT,JSON dependency-check:check
    - mvn -B $SONARQUBE_OPTS
          -Dsonar.host.url=https://sonarqube.inria.fr/sonarqube
          -Dsonar.login=$SONARQUBE_TOKEN
          -Dsonar.branch.name=${CI_COMMIT_BRANCH:-master}
          -Dsonar.qualitygate.wait=true
          sonar:sonar
  artifacts:
    paths:
      - target/dependency-check-report.html
    reports:
      junit:
        - target/dependency-check-junit.xml
