server:
  port: 8089
  error:
    include-message: always
    include-stacktrace: always

# Available endpoints for the monitoring
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus

spring:
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:19092
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:/unsecure-jwt-key.pub
analytics:
  creation-topic: dev.analytics.cmd.create
  deletion-topic: dev.analytics.cmd.delete

