#!/usr/bin/env bash

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Spotlessify java source files
mvn spotless:apply

# Add back the modified files to staging
echo "$FILES" | xargs git add

exit 0

